<template>
  <div class="container">
    <h4 style="width: 80%; text-align: justify; margin-left: 10%">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit.
      Consequuntur fuga magnam, nam qui quia tenetur unde!
      Corporis delectus dolores exercitationem inventore,
      ipsa modi non odio repellat tempora tenetur veritatis voluptatem.
    </h4>
    <p style="font-size: 20px; width: 80%; text-align: justify; margin-left: 10%"><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A blanditiis culpa dolor earum esse eveniet excepturi fugiat labore maiores modi, nisi nostrum odio officiis quia quibusdam sapiente tenetur ut, voluptatibus.</span><span>A aperiam aut blanditiis cumque delectus deleniti dolor doloribus eaque eligendi esse ex facere ipsa ipsam ipsum labore libero nesciunt nihil obcaecati quas rem, repudiandae similique suscipit tenetur vero voluptas.</span><span>Animi aperiam at commodi cumque ex nihil obcaecati odio, odit officiis perferendis placeat possimus quasi quibusdam quidem, sapiente sed sequi tempora ullam, vel vero. Deleniti earum et eveniet quaerat repellendus.</span><span>A autem consequatur culpa nam perferendis perspiciatis praesentium reiciendis tempore. Consequuntur debitis deleniti, dignissimos eius eligendi exercitationem harum itaque laborum, magni molestiae nam praesentium qui quisquam rem tempore veritatis voluptatum!</span><span>Aliquam asperiores dolor doloremque earum error eum excepturi fuga fugit illum molestias nostrum numquam odit, perspiciatis quaerat quia, quo reprehenderit totam unde vel voluptatum! Animi ex maiores nam porro voluptatum.</span><span>Amet cum deserunt dignissimos distinctio explicabo incidunt ipsam iure nesciunt, odit possimus repellendus reprehenderit suscipit unde voluptatem voluptatibus. Aliquid atque, cum explicabo maiores modi officiis quaerat ullam voluptates voluptatum! Fuga?</span></p>
    <p style="font-size: 20px; width: 80%; text-align: justify; margin-left: 10%"><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A blanditiis culpa dolor earum esse eveniet excepturi fugiat labore maiores modi, nisi nostrum odio officiis quia quibusdam sapiente tenetur ut, voluptatibus.</span><span>A aperiam aut blanditiis cumque delectus deleniti dolor doloribus eaque eligendi esse ex facere ipsa ipsam ipsum labore libero nesciunt nihil obcaecati quas rem, repudiandae similique suscipit tenetur vero voluptas.</span><span>Animi aperiam at commodi cumque ex nihil obcaecati odio, odit officiis perferendis placeat possimus quasi quibusdam quidem, sapiente sed sequi tempora ullam, vel vero. Deleniti earum et eveniet quaerat repellendus.</span><span>A autem consequatur culpa nam perferendis perspiciatis praesentium reiciendis tempore. Consequuntur debitis deleniti, dignissimos eius eligendi exercitationem harum itaque laborum, magni molestiae nam praesentium qui quisquam rem tempore veritatis voluptatum!</span><span>Aliquam asperiores dolor doloremque earum error eum excepturi fuga fugit illum molestias nostrum numquam odit, perspiciatis quaerat quia, quo reprehenderit totam unde vel voluptatum! Animi ex maiores nam porro voluptatum.</span><span>Amet cum deserunt dignissimos distinctio explicabo incidunt ipsam iure nesciunt, odit possimus repellendus reprehenderit suscipit unde voluptatem voluptatibus. Aliquid atque, cum explicabo maiores modi officiis quaerat ullam voluptates voluptatum! Fuga?</span></p>
    <p style="font-size: 20px; width: 80%; text-align: justify; margin-left: 10%"><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A blanditiis culpa dolor earum esse eveniet excepturi fugiat labore maiores modi, nisi nostrum odio officiis quia quibusdam sapiente tenetur ut, voluptatibus.</span><span>A aperiam aut blanditiis cumque delectus deleniti dolor doloribus eaque eligendi esse ex facere ipsa ipsam ipsum labore libero nesciunt nihil obcaecati quas rem, repudiandae similique suscipit tenetur vero voluptas.</span><span>Animi aperiam at commodi cumque ex nihil obcaecati odio, odit officiis perferendis placeat possimus quasi quibusdam quidem, sapiente sed sequi tempora ullam, vel vero. Deleniti earum et eveniet quaerat repellendus.</span><span>A autem consequatur culpa nam perferendis perspiciatis praesentium reiciendis tempore. Consequuntur debitis deleniti, dignissimos eius eligendi exercitationem harum itaque laborum, magni molestiae nam praesentium qui quisquam rem tempore veritatis voluptatum!</span><span>Aliquam asperiores dolor doloremque earum error eum excepturi fuga fugit illum molestias nostrum numquam odit, perspiciatis quaerat quia, quo reprehenderit totam unde vel voluptatum! Animi ex maiores nam porro voluptatum.</span><span>Amet cum deserunt dignissimos distinctio explicabo incidunt ipsam iure nesciunt, odit possimus repellendus reprehenderit suscipit unde voluptatem voluptatibus. Aliquid atque, cum explicabo maiores modi officiis quaerat ullam voluptates voluptatum! Fuga?</span></p>
    <p style="font-size: 20px; width: 80%; text-align: justify; margin-left: 10%"><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A blanditiis culpa dolor earum esse eveniet excepturi fugiat labore maiores modi, nisi nostrum odio officiis quia quibusdam sapiente tenetur ut, voluptatibus.</span><span>A aperiam aut blanditiis cumque delectus deleniti dolor doloribus eaque eligendi esse ex facere ipsa ipsam ipsum labore libero nesciunt nihil obcaecati quas rem, repudiandae similique suscipit tenetur vero voluptas.</span><span>Animi aperiam at commodi cumque ex nihil obcaecati odio, odit officiis perferendis placeat possimus quasi quibusdam quidem, sapiente sed sequi tempora ullam, vel vero. Deleniti earum et eveniet quaerat repellendus.</span><span>A autem consequatur culpa nam perferendis perspiciatis praesentium reiciendis tempore. Consequuntur debitis deleniti, dignissimos eius eligendi exercitationem harum itaque laborum, magni molestiae nam praesentium qui quisquam rem tempore veritatis voluptatum!</span><span>Aliquam asperiores dolor doloremque earum error eum excepturi fuga fugit illum molestias nostrum numquam odit, perspiciatis quaerat quia, quo reprehenderit totam unde vel voluptatum! Animi ex maiores nam porro voluptatum.</span><span>Amet cum deserunt dignissimos distinctio explicabo incidunt ipsam iure nesciunt, odit possimus repellendus reprehenderit suscipit unde voluptatem voluptatibus. Aliquid atque, cum explicabo maiores modi officiis quaerat ullam voluptates voluptatum! Fuga?</span></p>
    <p style="font-size: 20px; width: 80%; text-align: justify; margin-left: 10%"><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A blanditiis culpa dolor earum esse eveniet excepturi fugiat labore maiores modi, nisi nostrum odio officiis quia quibusdam sapiente tenetur ut, voluptatibus.</span><span>A aperiam aut blanditiis cumque delectus deleniti dolor doloribus eaque eligendi esse ex facere ipsa ipsam ipsum labore libero nesciunt nihil obcaecati quas rem, repudiandae similique suscipit tenetur vero voluptas.</span><span>Animi aperiam at commodi cumque ex nihil obcaecati odio, odit officiis perferendis placeat possimus quasi quibusdam quidem, sapiente sed sequi tempora ullam, vel vero. Deleniti earum et eveniet quaerat repellendus.</span><span>A autem consequatur culpa nam perferendis perspiciatis praesentium reiciendis tempore. Consequuntur debitis deleniti, dignissimos eius eligendi exercitationem harum itaque laborum, magni molestiae nam praesentium qui quisquam rem tempore veritatis voluptatum!</span><span>Aliquam asperiores dolor doloremque earum error eum excepturi fuga fugit illum molestias nostrum numquam odit, perspiciatis quaerat quia, quo reprehenderit totam unde vel voluptatum! Animi ex maiores nam porro voluptatum.</span><span>Amet cum deserunt dignissimos distinctio explicabo incidunt ipsam iure nesciunt, odit possimus repellendus reprehenderit suscipit unde voluptatem voluptatibus. Aliquid atque, cum explicabo maiores modi officiis quaerat ullam voluptates voluptatum! Fuga?</span></p>
    <p style="font-size: 20px; width: 80%; text-align: justify; margin-left: 10%"><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A blanditiis culpa dolor earum esse eveniet excepturi fugiat labore maiores modi, nisi nostrum odio officiis quia quibusdam sapiente tenetur ut, voluptatibus.</span><span>A aperiam aut blanditiis cumque delectus deleniti dolor doloribus eaque eligendi esse ex facere ipsa ipsam ipsum labore libero nesciunt nihil obcaecati quas rem, repudiandae similique suscipit tenetur vero voluptas.</span><span>Animi aperiam at commodi cumque ex nihil obcaecati odio, odit officiis perferendis placeat possimus quasi quibusdam quidem, sapiente sed sequi tempora ullam, vel vero. Deleniti earum et eveniet quaerat repellendus.</span><span>A autem consequatur culpa nam perferendis perspiciatis praesentium reiciendis tempore. Consequuntur debitis deleniti, dignissimos eius eligendi exercitationem harum itaque laborum, magni molestiae nam praesentium qui quisquam rem tempore veritatis voluptatum!</span><span>Aliquam asperiores dolor doloremque earum error eum excepturi fuga fugit illum molestias nostrum numquam odit, perspiciatis quaerat quia, quo reprehenderit totam unde vel voluptatum! Animi ex maiores nam porro voluptatum.</span><span>Amet cum deserunt dignissimos distinctio explicabo incidunt ipsam iure nesciunt, odit possimus repellendus reprehenderit suscipit unde voluptatem voluptatibus. Aliquid atque, cum explicabo maiores modi officiis quaerat ullam voluptates voluptatum! Fuga?</span></p>
    <p style="font-size: 20px; width: 80%; text-align: justify; margin-left: 10%"><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A blanditiis culpa dolor earum esse eveniet excepturi fugiat labore maiores modi, nisi nostrum odio officiis quia quibusdam sapiente tenetur ut, voluptatibus.</span><span>A aperiam aut blanditiis cumque delectus deleniti dolor doloribus eaque eligendi esse ex facere ipsa ipsam ipsum labore libero nesciunt nihil obcaecati quas rem, repudiandae similique suscipit tenetur vero voluptas.</span><span>Animi aperiam at commodi cumque ex nihil obcaecati odio, odit officiis perferendis placeat possimus quasi quibusdam quidem, sapiente sed sequi tempora ullam, vel vero. Deleniti earum et eveniet quaerat repellendus.</span><span>A autem consequatur culpa nam perferendis perspiciatis praesentium reiciendis tempore. Consequuntur debitis deleniti, dignissimos eius eligendi exercitationem harum itaque laborum, magni molestiae nam praesentium qui quisquam rem tempore veritatis voluptatum!</span><span>Aliquam asperiores dolor doloremque earum error eum excepturi fuga fugit illum molestias nostrum numquam odit, perspiciatis quaerat quia, quo reprehenderit totam unde vel voluptatum! Animi ex maiores nam porro voluptatum.</span><span>Amet cum deserunt dignissimos distinctio explicabo incidunt ipsam iure nesciunt, odit possimus repellendus reprehenderit suscipit unde voluptatem voluptatibus. Aliquid atque, cum explicabo maiores modi officiis quaerat ullam voluptates voluptatum! Fuga?</span></p>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({});
</script>
